/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.b0n541

import net.b0n541.skat.SkatPlayer
import net.b0n541.skat.SkatTable

fun main() {
    val table = SkatTable(listOf(SkatPlayer("Player One"), SkatPlayer("Player Two"), SkatPlayer("Player Three")))

    val game = table.newGame()
}
